import type { Metadata } from 'next';
import './styles/globals.css';
import './styles/font.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="max-w-screen-sm w-full mx-auto">
        <script src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=6fcecb1512dd4dc3a592c1037eab94c2&libraries=services&autoload=false"></script>

        {children}
      </body>
    </html>
  );
}
