import type { Metadata } from 'next';
import './styles/globals.css';
import './styles/font.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import Script from 'next/script';

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head></head>
      <body className="max-w-screen-sm w-full mx-auto">
        {children}
        <Script
          src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=6fcecb1512dd4dc3a592c1037eab94c2&autoload=false"
          strategy="afterInteractive" // 페이지가 로드된 후 실행
        />
      </body>
    </html>
  );
}
