import type { Metadata } from 'next';
import './styles/globals.css';
import './styles/font.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-screen-sm w-full mx-auto">{children}</body>
    </html>
  );
}
